/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_thedutchmc_betterplayer_natives_DeepSpeechNativeInterface */

#ifndef _Included_nl_thedutchmc_betterplayer_natives_DeepSpeechNativeInterface
#define _Included_nl_thedutchmc_betterplayer_natives_DeepSpeechNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_thedutchmc_betterplayer_natives_DeepSpeechNativeInterface
 * Method:    callNativeMethod
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_nl_thedutchmc_betterplayer_natives_DeepSpeechNativeInterface_callNativeMethod
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
