# BetterPlayer configuration file
# The open source Discord music bot

# Your bot token
botToken: ""

# API
useGoogleApi: false
googleApikey: ""

#Guild configuration
dbHost: ""
dbName: ""
dbUsername: ""
dbPassword: ""