# BetterPlayer configuration file
# The open source Discord music bot

# Your bot token
botToken: ""

# API
useGoogleApi: false
googleApikey: ""

#Guild configuration
dbHost: ""
dbName: ""
dbUsername: ""
dbPassword: ""

#KSoft API
#Leave as "" if you do not have a KSoft API token
#This is only required if you want to use the lyrics command
ksoftApiToken: ""